base_link2sensor_kit_base_link:
  x: 0.9
  y: 0.0
  z: 2.0
  roll: -0.001
  pitch: 0.015
  yaw: -0.0364
base_link2livox_front_right_base_link:
  x: 3.290
  y: -0.65485
  z: 0.3216
  roll: 0.0
  pitch: 0.0
  yaw: -0.872664444
base_link2livox_front_left_base_link:
  x: 3.290
  y: 0.65485
  z: 0.3016
  roll: -0.021
  pitch: 0.05
  yaw: 0.872664444
base_link2velodyne_rear_base_link:
  x: -0.358
  y: 0.0
  z: 1.631
  roll: -0.02
  pitch: 0.7281317
  yaw: 3.141592
