sensor_kit_base_link2camera0:
  x: 0.10731
  y: 0.56343
  z: -0.27697
  roll: -0.025
  pitch: 0.315
  yaw: 1.035
sensor_kit_base_link2camera1:
  x: -0.10731
  y: -0.56343
  z: -0.27697
  roll: -0.025
  pitch: 0.32
  yaw: -2.12
sensor_kit_base_link2camera2:
  x: 0.10731
  y: -0.56343
  z: -0.27697
  roll: -0.00
  pitch: 0.335
  yaw: -1.04
sensor_kit_base_link2camera3:
  x: -0.10731
  y: 0.56343
  z: -0.27697
  roll: 0.0
  pitch: 0.325
  yaw: 2.0943951
sensor_kit_base_link2camera4:
  x: 0.07356
  y: 0.0
  z: -0.0525
  roll: 0.0
  pitch: -0.03
  yaw: -0.005
sensor_kit_base_link2camera5:
  x: -0.07356
  y: 0.0
  z: -0.0525
  roll: 0.0
  pitch: -0.01
  yaw: 3.125
sensor_kit_base_link2traffic_light_right_camera:
  x: 0.05
  y: -0.0175
  z: -0.1
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
sensor_kit_base_link2traffic_light_left_camera:
  x: 0.05
  y: 0.0175
  z: -0.1
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
sensor_kit_base_link2velodyne_top_base_link:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 1.575
sensor_kit_base_link2velodyne_left_base_link:
  x: 0.0
  y: 0.56362
  z: -0.30555
  roll: -0.02
  pitch: 0.71
  yaw: 1.575
sensor_kit_base_link2velodyne_right_base_link:
  x: 0.0
  y: -0.56362
  z: -0.30555
  roll: -0.01
  pitch: 0.71
  yaw: -1.580
sensor_kit_base_link2gnss:
  x: -0.1
  y: 0.0
  z: -0.2
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
sensor_kit_base_link2imu_tamagawa:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 3.14159265359
  pitch: 0.0
  yaw: 3.14159265359
